---

- name: apt | sketchy packages dependencies - certificate
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ssl-cert
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- set_fact:
    ssl_user: ssl-cert
    ssl_privatedir: /etc/ssl/private
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- set_fact:
    ssl_user: root
    ssl_privatedir: /etc/ssl
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- stat: path=/etc/ssl/{{ ansible_fqdn }}.crt
  register: localsslcert
- name: Generale SSL self-signed certificate
  command: openssl req -x509 -nodes -sha256 -days {{ sketchy_certduration }} -newkey rsa:2048 -subj "{{ sketchy_certinfo }}/CN={{ ansible_fqdn }}" -keyout {{ ssl_privatedir }}/{{ ansible_fqdn }}.key -out /etc/ssl/{{ ansible_fqdn }}.crt
  when: not localsslcert.stat.exists
- file: "path={{ ssl_privatedir }}/{{ ansible_fqdn }}.key owner=root group={{ ssl_user }} mode=0440"

