---

- name: set certificate cn to ansible fqdn
  set_fact:
    certificate_cn: "{{ ansible_fqdn }}"

- name: checking environment if travis
  command: "env"
  register: env
  changed_when: false
- name: set certificate cn to travis short fqdn
  set_fact:
    certificate_cn: "testing-travis.internal"
  when: env is defined and env.stdout.find('TRAVIS=true') != -1

- name: apt | sketchy packages dependencies - certificate
  apt: name=ssl-cert state=present update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: check if existing certificate
  stat: path=/etc/ssl/{{ ansible_fqdn }}.crt
  register: localsslcert
- name: Generate SSL self-signed certificate
  command: >
    openssl req -x509 -nodes -sha256 -days {{ sketchy_certduration }} -newkey rsa:2048
      -subj "{{ sketchy_certinfo }}/CN={{ certificate_cn }}"
      -keyout {{ ssl_privatedir }}/{{ ansible_fqdn }}.key
      -out /etc/ssl/{{ ansible_fqdn }}.crt
  when: not localsslcert.stat.exists
- name: ensure permissions on key file are correct
  file: "path={{ ssl_privatedir }}/{{ ansible_fqdn }}.key owner=root group={{ ssl_user }} mode=0440"
