---

- name: yum | sketchy dependencies packages install
  yum: name="{{item}}" state=present update_cache=yes
  with_items: "{{ sketchy_pkgs }}"

#- name: Redhat | Ensure yum-cron is running and enabled on boot.
#  service: name=yum-cron state=started enabled=yes

