---
- set_fact:
    redis_svc: redis
    redis_conf: /etc/redis.conf
    supervisor_svc: supervisord
    supervisor_confdir: /etc/supervisord.d
    supervisor_ext: ini
    nginx_confdir: /etc/nginx/conf.d
    ssl_user: root
    ssl_privatedir: /etc/ssl

- name: yum | sketchy dependencies packages install
  yum: name="{{item}}" state=present update_cache=yes
  with_items:
    - git
    - python
    - python-pip
    - libxslt-devel
    - libxml2-devel
    - redis
    - mariadb-libs
    - mariadb
    - "@Development tools"
    - python-devel
    - mariadb-devel
    - python-gunicorn
    - supervisor
    - nginx

#- name: Redhat | Ensure yum-cron is running and enabled on boot.
#  service: name=yum-cron state=started enabled=yes

