---

- name: restart supervisor
  service: name={{ supervisor_svc }} state=restarted sleep=5

- name: restart redis
  service: name={{ redis_svc }} state=restarted

- name: restart nginx
  service: name=nginx state=restarted
